apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: ingress-basic
  name: aksisfar-eastus2-cloudapp-azure-com-staging
spec:
  secretName: aksisfar-eastus2-cloudapp-azure-com-staging
  dnsNames:
  - aksisfar.eastus2.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - aksisfar.eastus2.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  