apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: ingress-basic
  name: newaz-eastus-cloudapp-azure-com-staging
spec:
  secretName: newaz-eastus-cloudapp-azure-com-staging
  dnsNames:
  - newaz.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - newaz.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  
